/** @format */
// import React_img1 from "../pics/ARF-logo.png";

const Data = [
	{
		id: "12",
		title: "Mdsd",
		category: "Vanilla js",
		status: "$1",
		img: "https://via.placeholder.com/640x360",
		desc: "MongoDB A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
		tags: "Js.",
	},
	{
		id: "1",
		title: "Movie App",
		category: "React.js",
		status: "running",
		img: "https://areful.com/react/images/movie-app.png",
		desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Optio voluptatibus maxime sint laborum corrupti non.",
		tags: ["1", "2", "3"],
		detailsExplain: "https://github.com/iAreful/React-Movie-app",
		liveLink: "https://areful.com/react/movie-app/",
		githubRepo: "https://github.com/iAreful/React-Movie-app",
	},
	{
		id: "2",
		title: "Upma",
		category: "React.js",
		status: "$1",
		img: "https://areful.com/react/images/notepad-app.png",
		desc: " A quintessential South Indian Breakfast! Made with protein-packed urad dal and semolina followed by crunchy veggies and curd, this recipe makes for a hearty morning meal. With some grated coconut on top, it gives a beautiful south-Indian flavour.",
		tags: "Js.",
		detailsExplain: "https://github.com/iAreful/Notepad-app-react",
		liveLink: "https://www.areful.com/react/notepad-app/",
		githubRepo: "https://github.com/iAreful/Notepad-app-react",
	},
	{
		id: "3",
		title: "Portfolio v1",
		category: "React.js",
		status: "complete",
		img: "https://areful.com/react/images/portfolio-app.png",
		desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. You can also add paneer to this recipe to amp up the nutritional value and make it, even more, protein-dense",
		tags: "Js.",
		detailsExplain: "https://www.arful.com",
		liveLink: "https://www.arful.com",
		githubRepo: "https://www.github.com/areful/portfolio-v1r",
	},
	{
		id: "4",
		title: "next js Blog app with MongoDB",
		category: "Next.js",
		status: "build",
		img: "https://areful.com/react/images/next-js-blog-app.png",
		desc: "A classic dish that never goes out of style. The quintessential chana kulcha  needs only a few ingredients - cumin powder, ginger, coriander powder, carom powder and some mango powder, which is what gives the chana it's sour and tangy taste.",
		tags: "Js.",
		detailsExplain: "https://github.com/iAreful/nextjs-blog-app-with-mongodb",
		liveLink: "https://github.com/iAreful/nextjs-blog-app-with-mongodb",
		githubRepo: "https://github.com/iAreful/nextjs-blog-app-with-mongodb",
	},
	{
		id: "5",
		title: "Next-Js-taiwind-CSS-starter",
		category: "Next.js",
		status: "$1",
		img: "https://via.placeholder.com/640x360",
		desc: "Eggs are a versatile food that can be cooked for any meal of the day. From breakfast to dinner, it can be a go-to food. Here is a mildly-spiced egg curry made with garlic, onions, a whole lot of kasuri methi, fresh cream, yogurt and fresh coriander.",
		tags: "Js.",
		detailsExplain:
			"https://github.com/iAreful/Next-Js-taiwind-CSS-starter-v1.11",
		liveLink: "https://github.com/iAreful/Next-Js-taiwind-CSS-starter-v1.11",
		githubRepo: "https://github.com/iAreful/Next-Js-taiwind-CSS-starter-v1.11",
	},
	{
		id: "6",
		title: "next js ecommerce",
		category: "Next.js",
		status: "build",
		img: "https://areful.com/react/images/next-js-ecommerce.png",
		desc: "Don't get intimidated by the list of ingredients because not only are already in your kitchen cabinet, but also because all they'll need is 20 minutes of your time. Chunks of cottage cheese cooked in some exciting spices, yogurt and a pinch of sugar.",
		tags: "Js.",
		detailsExplain: "https://github.com/iAreful/Next-JS-Ecommerce-Store",
		liveLink: "http://next-js-ecommerce-store-one.vercel.app/",
		githubRepo: "https://github.com/iAreful/Next-JS-Ecommerce-Store",
	},
	{
		id: "7",
		title: "Node JS Rest API",
		category: "Node.js",
		status: "build",
		img: "https://areful.com/react/images/nodejs-resat-api.png",
		desc: "Get your daily dose of perfect protein. Pieces of surmai fish marinated in garlic, cumin, fennel, curry leaves and tomatoes are pan-fried in refined oil and served hot. This fish fry recipe has a host of delectable spices used for marination giving it a unique touch.",
		tags: "Js.",
		detailsExplain: "https://github.com/iAreful/node-js-rest-api",
		liveLink: "https://github.com/iAreful/node-js-rest-api",
		githubRepo: "https://github.com/iAreful/node-js-rest-api",
	},
	{
		id: "8",
		title: "Dum Alloo",
		category: "Node.js",
		status: "$1",
		img: "https://via.placeholder.com/640x360",
		desc: "Your family will thank you for this absolutely fantastic bowl of dum aloo cooked Lakhnawi style. Take some potatoes, crumbled paneer, kasuri methi, butter, onions and some ghee.",
		tags: "Js.",
		detailsExplain: "https://github.com/iAreful/node-js-rest-api",
		liveLink: "https://github.com/iAreful/node-js-rest-api",
		githubRepo: "https://github.com/iAreful/node-js-rest-api",
	},
	{
		id: "9",
		title: "Malai Kofta",
		category: "Node.js",
		status: "$1",
		img: "https://via.placeholder.com/640x360",
		desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
		tags: "Js.",
	},
	{
		id: "10",
		title: "Malai Kofta",
		category: "Express.js",
		status: "$1",
		img: "https://via.placeholder.com/640x360",
		desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
		tags: "Js.",
	},
	{
		id: "11",
		title: "Mdsd",
		category: "MongoDB",
		status: "$1",
		img: "https://via.placeholder.com/640x360",
		desc: "MongoDB A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
		tags: "Js.",
	},
];

export default Data;
